name: Remote Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Dit zorgt ervoor dat hij direct op jouw ubuntu server activeert
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Restart App
        run: |
          cd /var/www/anystats
          
          # Lokale wijzigingen terugdraaien om git conflicten te voorkomen
          git reset --hard HEAD
          
          # De nieuwste commits ophalen
          git pull origin main
          
          # Next.js dependencies installeren en builden
          npm install
          npm run build
          
          # Je applicatie herstarten met PM2
          pm2 restart anystats || pm2 start npm --name "anystats" -- start
